//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigex.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class preguntasExaman
    {
        public int idpreguntasExamen { get; set; }
        public int idTest { get; set; }
        public string Nombre { get; set; }
        public string Valor { get; set; }
        public string Descripcion { get; set; }
        public bool status { get; set; }
        public int idTipoPregunta { get; set; }
        public string RespuestaCorrecta { get; set; }
    
        public virtual Examan Examan { get; set; }
        public virtual TipoPregunta TipoPregunta { get; set; }
    }
}
